version: '2'
services:
  node-server:
    build: .
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - .:/usr/src/app/:rw
      - vendor:/usr/src/app/node_modules
volumes:
  vendor: