version: "2"
services:
  api-server:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
        - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: ehazlett/mongodb
    volumes:
      - ./data/mongodb:/data/db